name: Testes na API do "O Senhor dos Aneis" com Postman
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Check out Git repositor
        uses: actions/checkout@v2
        
      - name: Install newman
        run: npm install -g newman
        
      - name: Install newman-reporter-allure
        run: npm install -g newman-reporter-allure
        
      - name: Run the Postman's tests
        run: | 
          newman run "postman_collection.json" -r allure
          
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
